### ISSUE TITLE
Step 2

### ISSUE THREAD

**Issue by JHallPD** [ukari/cors-proxy-webpack-plugin#4]
How do you do step 2? node_modules/.bin/cors-proxy-server --config webpack.config.js is not a valid command 

and the webpack script with concurrently errors out not finding either of the servers in its script.

How do i actually use the command line to do this?

**Comment by JHallPD** [comment]
I have changed around the syntax and now i get 
"ReferenceError: CorsProxyWebpackPlugin is not defined"

How do I fix this?

**Comment by ukari** [comment]
I have read you questions but I still can't infer how to resolve them.

Have you done Step 0? For Step 2, did you use the right path for `node_modules` when run the command in command line? and the `npm script` way need to edit your `package.json` file, [npm script doc](https://docs.npmjs.com/misc/scripts)

Where is the ReferenceError occurs, which step, in the browser or in the command line?

**Comment by ukari** [comment]
and which version you use now? npm released version or directly use the master branch in github?

**Comment by JHallPD** [comment]
Hey Thanks for the quick reply. I had followed step 0 step 1 and on step 2 cant get it to work. However this is just for an interview assignment where im trying to send twitter api requests without a server. Im just going to give up on this since it seems to be nearly impossible to make api requests to twitter without a server
